"""Add full hub schema from PDF

Revision ID: 487bde7a8fcd
Revises: ee740a6dd9fa
Create Date: 2026-05-24 23:45:18.572412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '487bde7a8fcd'
down_revision: Union[str, Sequence[str], None] = 'ee740a6dd9fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_url', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('device_tokens', postgresql.ARRAY(sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'device_tokens')
    op.drop_column('users', 'avatar_url')
    # ### end Alembic commands ###
