// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB38sQmMagtk0G7mRjxtdFRnlDguvVy4dU',
    appId: '1:694919401031:web:687edf3749303f0b6aab62',
    messagingSenderId: '694919401031',
    projectId: 'smarthub-c71a6',
    authDomain: 'smarthub-c71a6.firebaseapp.com',
    storageBucket: 'smarthub-c71a6.firebasestorage.app',
    measurementId: 'G-EDPLHSCEZB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBb74P77cwSaLbosSiJbNl46IxdrTpQ3m0',
    appId: '1:694919401031:android:f3e24c54c3e9da6a6aab62',
    messagingSenderId: '694919401031',
    projectId: 'smarthub-c71a6',
    storageBucket: 'smarthub-c71a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcR7w8YLt0i70RCI_KduizgrDkNTwyfvc',
    appId: '1:694919401031:ios:5dd6c04c3b5cefac6aab62',
    messagingSenderId: '694919401031',
    projectId: 'smarthub-c71a6',
    storageBucket: 'smarthub-c71a6.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcR7w8YLt0i70RCI_KduizgrDkNTwyfvc',
    appId: '1:694919401031:ios:5dd6c04c3b5cefac6aab62',
    messagingSenderId: '694919401031',
    projectId: 'smarthub-c71a6',
    storageBucket: 'smarthub-c71a6.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB38sQmMagtk0G7mRjxtdFRnlDguvVy4dU',
    appId: '1:694919401031:web:8ac77ed619a31dd06aab62',
    messagingSenderId: '694919401031',
    projectId: 'smarthub-c71a6',
    authDomain: 'smarthub-c71a6.firebaseapp.com',
    storageBucket: 'smarthub-c71a6.firebasestorage.app',
    measurementId: 'G-7RBLTXFTHG',
  );
}
